added fix for kernel 6.0.0, but after that other errors appeared related to changes in mac80211.h
  CC [M]  drivers/net/wireless/rtl8189fs/hal/phydm/phydm_soml.o
drivers/net/wireless/xradio/main.c:152:30: error: initialization of ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, u64)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, long long unsigned int)’} from incompatible pointer type ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, u32)’ {aka ‘void (*)(struct ieee80211_hw *, struct ieee80211_vif *, struct ieee80211_bss_conf *, unsigned int)’} [-Werror=incompatible-pointer-types]
  152 |         .bss_info_changed  = xradio_bss_info_changed,
      |                              ^~~~~~~~~~~~~~~~~~~~~~~
drivers/net/wireless/xradio/main.c:152:30: note: (near initialization for ‘xradio_ops.bss_info_changed’)
drivers/net/wireless/xradio/main.c:155:30: error: initialization of ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, unsigned int,  u16,  const struct ieee80211_tx_queue_params *)’ {aka ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, unsigned int,  short unsigned int,  const struct ieee80211_tx_queue_params *)’} from incompatible pointer type ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, u16,  const struct ieee80211_tx_queue_params *)’ {aka ‘int (*)(struct ieee80211_hw *, struct ieee80211_vif *, short unsigned int,  const struct ieee80211_tx_queue_params *)’} [-Werror=incompatible-pointer-types]
  155 |         .conf_tx           = xradio_conf_tx,
      |                              ^~~~~~~~~~~~~~
drivers/net/wireless/xradio/main.c:155:30: note: (near initialization for ‘xradio_ops.conf_tx’)
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:249: drivers/net/wireless/xradio/main.o] Error 1
make[3]: *** [scripts/Makefile.build:465: drivers/net/wireless/xradio] Error 2
make[3]: *** Waiting for unfinished jobs....